/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;



import controllers.ImageController;
import controllers.ItemController;
import DataAccess.*;
import controllers.OrderController;
import controllers.SearchController;
import models.Enums;
import models.ItemModel;
import models.SearchModel;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.text.html.HTML;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Owner
 */
public class homepageView extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public homepageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoplify");
        setPreferredSize(new java.awt.Dimension(750, 570));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton10.setText("Dairy");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton13.setText("Meats");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton4.setText("Fruit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("vegetables");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Drinks");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Desserts");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Bread");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/toolbar_find.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/user.png"))); // NOI18N
        jButton2.setText("Login/Signup");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/shopping_cart_webshop.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(881, 493));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(881, 493));
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));
        jScrollPane2.setViewportView(jPanel4);

        jLayeredPane1.add(jScrollPane2);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel11);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setLayout(new javax.swing.OverlayLayout(jPanel5));
        jScrollPane3.setViewportView(jPanel5);

        jLayeredPane1.add(jScrollPane3);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));
        jScrollPane4.setViewportView(jPanel6);

        jLayeredPane1.add(jScrollPane4);

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel7.setLayout(new javax.swing.OverlayLayout(jPanel7));
        jScrollPane5.setViewportView(jPanel7);

        jLayeredPane1.add(jScrollPane5);

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));
        jScrollPane6.setViewportView(jPanel8);

        jLayeredPane1.add(jScrollPane6);

        jScrollPane8.setBorder(null);
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel10.setLayout(new javax.swing.OverlayLayout(jPanel10));
        jScrollPane8.setViewportView(jPanel10);

        jLayeredPane1.add(jScrollPane8);

        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel9.setLayout(new javax.swing.OverlayLayout(jPanel9));
        jScrollPane7.setViewportView(jPanel9);

        jLayeredPane1.add(jScrollPane7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jLayeredPane1.add(jScrollPane1);

        jPanel3.add(jLayeredPane1);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/breamcatcher.regular.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/barcode.png"))); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem3.setText("jMenuItem3");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Shoplify");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int flag1 = 0;
    ArrayList<ItemModel> itemsList = ItemController.getItems();
    int i = itemsList.size();
    JButton buttons[] = new JButton[70];
    //JButton btn1 = new JButton();
    //JButton btn2 = new JButton();
//    ItemModel Item = new ItemModel(;

    ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            //Object button = e.getSource();
            for(int i=0; i<70; i++) {
                if (e.getSource() == buttons[i]) {
                    //int test = Integer.parseInt(button.toString());
                    //System.out.println(button.toString());
                    System.out.println(i);
                    try {
                        OrderController.addItemToOrder(i);
                    } catch (ClassNotFoundException e1) {
                        e1.printStackTrace();
                    }
                    //            button.
                }
            }
            if (e.getSource() instanceof JButton) {
//                if (e.getSource() == button[index])
////                String text = ((JButton) e.getSource()).getText();
//                System.out.print(text);
            }
        }
    };
    private void render(String cat){
        jPanel4.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=0;
        if(flag1 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Meat) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel4.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel4);

                }

                index = itemsList.indexOf(item);
            }
        }
        flag1 = 1;
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loginView frame = new loginView();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_jButton13ActionPerformed
        render("Meat");


    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String searchString = jTextField1.getText();
        ArrayList<ItemModel> searchList = SearchController.enterItemToSearch("bread");


        jPanel2.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel search: searchList) {
                //System.out.println(search); -- only print out the address
                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + search.getName() + "<br>" + search.getPrice()+ "</html>");
                System.out.println(search.getImageName());
                ImageIcon imageIcon = new ImageIcon(search.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(search.getName()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel2.add(itemPanel);

        }
        jPanel2.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        ArrayList<ItemModel> itemsList = ItemController.getItems();
        jPanel5.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel item: itemsList) {
            if (item.getCategory() == Enums.Category.Dairy) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice()+ "</html>");

                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(item.getItemID()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel5.add(itemPanel);


            }
        }
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {//GEN-FIRST:event_jButton3ActionPerformed
        shoppingCartView frame = new shoppingCartView();
        frame.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<ItemModel> itemsList = ItemController.getItems();
        jPanel6.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel item: itemsList) {
            if (item.getCategory() == Enums.Category.Fruit) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice()+ "</html>");

                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(item.getItemID()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));
                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel6.add(itemPanel);


            }
        }
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ArrayList<ItemModel> itemsList = ItemController.getItems();
        jPanel7.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel item: itemsList) {
            if (item.getCategory() == Enums.Category.Vegetables) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice()+ "</html>");

                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(item.getItemID()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));
                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel7.add(itemPanel);


            }
        }
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ArrayList<ItemModel> itemsList = ItemController.getItems();
        jPanel8.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel item: itemsList) {
            if (item.getCategory() == Enums.Category.Drink) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice()+ "</html>");

                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(item.getItemID()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));
                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel8.add(itemPanel);


            }
        }
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(true);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ArrayList<ItemModel> itemsList = ItemController.getItems();
        jPanel9.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel item: itemsList) {
            if (item.getCategory() == Enums.Category.Dessert) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice()+ "</html>");

                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(item.getItemID()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));
                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel9.add(itemPanel);


            }
        }
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(true);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ArrayList<ItemModel> itemsList = ItemController.getItems();
        jPanel10.setLayout(new GridLayout(0,3));
        JButton itemlist1 = null;
        JPanel itemPanel =null;
        JLabel itemLabel =null;
        for(ItemModel item: itemsList) {
            if (item.getCategory() == Enums.Category.Bread) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                itemlist1 = new JButton();
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice()+ "</html>");

                String imagePath = item.getImagePath();
                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120,  Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back

                itemlist1.setIcon(imageIcon); // NOI18N
                itemlist1.setName(String.valueOf(item.getItemID()));
                itemlist1.setBorder(null);
                itemlist1.setBorderPainted(false);
                itemlist1.setContentAreaFilled(false);
                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
                itemPanel.add(itemlist1, c);

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel10.add(itemPanel);


            }
        }
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(true);
        jPanel11.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();
        return resizedImg;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
