/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;



import controllers.ItemController;
import controllers.OrderController;
import controllers.SearchController;
import models.Enums;
import models.ItemModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.ArrayList;

/**
 *
 * @author Owner
 */
public class homepageView extends JFrame {

    /**
     * Creates new form Homepage
     */
//    AccountModel accountModel = Global.CURRENT_ACCOUNT;
//    String userFirstName = accountModel.getUserModel().getFirstName();
//    String userLastName = accountModel.getUserModel().getLastName();

    public homepageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new JToggleButton();
        jMenu4 = new JMenu();
        jPanel1 = new JPanel();
        jButton10 = new JButton();
        jButton13 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jButton8 = new JButton();
        jTextField1 = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jPanel3 = new JPanel();
        jLayeredPane1 = new JLayeredPane();
        jScrollPane2 = new JScrollPane();
        jPanel4 = new JPanel();
        jPanel11 = new JPanel();
        jSplitPane1 = new JSplitPane();
        jScrollPane3 = new JScrollPane();
        jPanel5 = new JPanel();
        jScrollPane4 = new JScrollPane();
        jPanel6 = new JPanel();
        jScrollPane5 = new JScrollPane();
        jPanel7 = new JPanel();
        jScrollPane6 = new JScrollPane();
        jPanel8 = new JPanel();
        jScrollPane8 = new JScrollPane();
        jPanel10 = new JPanel();
        jScrollPane7 = new JScrollPane();
        jPanel9 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jPanel2 = new JPanel();
        jButton9 = new JButton();
        jLabel2 = new JLabel();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenuItem1 = new JMenuItem();
        jMenu2 = new JMenu();
        jMenuItem2 = new JMenuItem();
        jMenu3 = new JMenu();
        jMenuItem3 = new JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoplify");
        setPreferredSize(new Dimension(950, 570));

        jPanel1.setBorder(BorderFactory.createTitledBorder(""));

        jButton10.setText("Dairy");
        jButton10.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton13.setText("Meats");
        jButton13.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton4.setText("Fruit");
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("vegetables");
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Drinks");
        jButton6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Desserts");
        jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Bread");
        jButton8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jButton10, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton13, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .addComponent(jButton6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton13)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.setHorizontalAlignment(JTextField.RIGHT);
        jTextField1.setText("Search");
        jTextField1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new ImageIcon(getClass().getResource("/pics/toolbar_find.png"))); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new ImageIcon(getClass().getResource("/pics/user.png"))); // NOI18N
        jButton2.setText("Login/Signup");
        jButton2.setBorder(BorderFactory.createCompoundBorder());
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new ImageIcon(getClass().getResource("/pics/shopping_cart_webshop.png"))); // NOI18N
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        jPanel3.setBorder(BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new Dimension(881, 493));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new OverlayLayout(jPanel3));

        jLayeredPane1.setPreferredSize(new Dimension(881, 493));
        jLayeredPane1.setLayout(new OverlayLayout(jLayeredPane1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setLayout(new OverlayLayout(jPanel4));
        jScrollPane2.setViewportView(jPanel4);

        jLayeredPane1.add(jScrollPane2);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setOrientation(JSplitPane.VERTICAL_SPLIT);

        GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel11);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setLayout(new OverlayLayout(jPanel5));
        jScrollPane3.setViewportView(jPanel5);

        jLayeredPane1.add(jScrollPane3);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel6.setLayout(new OverlayLayout(jPanel6));
        jScrollPane4.setViewportView(jPanel6);

        jLayeredPane1.add(jScrollPane4);

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel7.setLayout(new OverlayLayout(jPanel7));
        jScrollPane5.setViewportView(jPanel7);

        jLayeredPane1.add(jScrollPane5);

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel8.setLayout(new OverlayLayout(jPanel8));
        jScrollPane6.setViewportView(jPanel8);

        jLayeredPane1.add(jScrollPane6);

        jScrollPane8.setBorder(null);
        jScrollPane8.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel10.setLayout(new OverlayLayout(jPanel10));
        jScrollPane8.setViewportView(jPanel10);

        jLayeredPane1.add(jScrollPane8);

        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel9.setLayout(new OverlayLayout(jPanel9));
        jScrollPane7.setViewportView(jPanel9);

        jLayeredPane1.add(jScrollPane7);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jLayeredPane1.add(jScrollPane1);

        jPanel3.add(jLayeredPane1);

        jButton9.setIcon(new ImageIcon(getClass().getResource("/pics/breamcatcher.regular.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setMargin(new Insets(0, 0, 0, 0));
        jButton9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/pics/barcode.png"))); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem3.setText("jMenuItem3");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton9, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312)
                        .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Shoplify");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //JButton btn1 = new JButton();
    //JButton btn2 = new JButton();
//    ItemModel Item = new ItemModel(;

    ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            //Object button = e.getSource();
            for(int i=0; i<70; i++) {
                if (e.getSource() == buttons[i]) {
                    int btNum = Integer.valueOf(buttons[i].getName());
                    //System.out.println(button.toString());
//                    System.out.print("!!!!!!Button " + buttons[i].getName() + " pressed!!!!!1");
                    System.out.println(i);
                    try {
                        //todo pass in quantity!
                        int quantity = 1;
                        OrderController.addItemToOrder(btNum, quantity);
                    } catch (ClassNotFoundException e1) {
                        e1.printStackTrace();
                    }
                    //            button.
                }
            }
            if (e.getSource() instanceof JButton) {
//                if (e.getSource() == button[index])
////                String text = ((JButton) e.getSource()).getText();
//                System.out.print(text);
            }
        }
    };
    ActionListener listener2 = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            //Object button = e.getSource();
            for(int i=0; i<70; i++) {
                if (e.getSource() == searchButtons[i]) {
                    int btNum = Integer.valueOf(searchButtons[i].getName());
                    //System.out.println(button.toString());
//                    System.out.print("!!!!!!Button " + buttons[i].getName() + " pressed!!!!!1");
                    System.out.println(i);
                    try {
                        //todo pass in quantity!
                        int quantity = 1;
                        OrderController.addItemToOrder(btNum, quantity);
                    } catch (ClassNotFoundException e1) {
                        e1.printStackTrace();
                    }
                    //            button.
                }
            }
            if (e.getSource() instanceof JButton) {
//                if (e.getSource() == button[index])
////                String text = ((JButton) e.getSource()).getText();
//                System.out.print(text);
            }
        }
    };
    int flag1 = 0;
    ArrayList<ItemModel> itemsList = ItemController.getItems();
    int i = itemsList.size();
    JButton buttons[] = new JButton[70];

    private void render1(String cat){
        jPanel4.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=0;
        jPanel4.removeAll();
//        if(flag1 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Meat) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel4.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel4);
                    index++;
//                }


            }
        }
        flag1 = 1;
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }
    JButton buttons2[] = new JButton[70];
    int flag_2=0;
    private void render2(String cat){
        jPanel5.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=10;
        jPanel5.removeAll();
//        if(flag_2 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Dairy) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel5.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel5);
                    index++;
//                }


            }
        }
        flag_2 = 1;
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }
    int flag3=0;
    private void render3(String cat){
        jPanel6.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=30;
        jPanel6.removeAll();
//        if(flag3 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Fruit) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel6.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel6);
                    index++;
//                }


            }
        }
        flag3 = 1;
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }

    int flag4=0;
    private void render4(String cat){
        jPanel7.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=40;
        jPanel7.removeAll();

//   if(flag4 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Vegetables) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel7.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel7);
                    index++;
                }


//            }
        }
        flag4 = 1;
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }

    int flag5=0;
    private void render5(String cat){
        jPanel8.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=40;
        jPanel8.removeAll();
//        if(flag5 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Drink) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel8.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel8);
                    index++;
                }


            }
//        }
        flag5 = 1;
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(true);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }
    int flag6=0;
    private void render6(String cat){
        jPanel9.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=40;
        jPanel9.removeAll();
//        if(flag6 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Dessert) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel9.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel9);
                    index++;
                }


//            }
        }
        flag6 = 1;
        jPanel9.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);

        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }

    int flag7=0;
    private void render7(String cat){
        jPanel10.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        int index=40;
        jPanel10.removeAll();
//        if(flag7 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Bread) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel10.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel10);
                    index++;
//                }


            }
        }
        flag7 = 1;
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(true);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }

    int flag8=0;
    private void render8(String cat){
        jPanel10.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        jPanel10.removeAll();
        int index=40;
//        if(flag8 == 0) {
            for (ItemModel item : itemsList) {
                if (item.getCategory() == Enums.Category.Bread) {

                    itemPanel = new JPanel();
                    itemPanel.setLayout(new GridBagLayout());
                    GridBagConstraints c = new GridBagConstraints();
                    //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                    buttons[index] = new JButton();
                    buttons[index].addActionListener(listener);
                    itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                    ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                    imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                    buttons[index].setIcon(imageIcon); // NOI18N
                    buttons[index].setName(String.valueOf(item.getItemID()));
                    //                itemlist1.setBorder(null);
                    //                itemlist1.setBorderPainted(false);
                    //                itemlist1.setContentAreaFilled(false);
                    //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                    c.fill = GridBagConstraints.BOTH;
                    c.ipady = 40;      //make this component tall
                    c.weightx = 0.0;
                    c.gridwidth = 3;
                    c.gridx = 0;
                    c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                    itemPanel.add(buttons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                    c.fill = GridBagConstraints.CENTER;
                    c.weightx = 0.0;
                    c.gridx = 0;
                    c.gridy = 1;
                    itemPanel.add(itemLabel, c);
                    jPanel10.add(itemPanel);
                    jScrollPane2.setViewportView(jPanel10);
                    index++;
//                }


            }
        }
        flag4 = 1;
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(true);
        jPanel11.setVisible(false);
        repaint();
        validate();
    }
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loginView frame = new loginView();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(ActionEvent evt){//GEN-FIRST:event_jButton13ActionPerformed
        render1("Meat");
        repaint();
        validate();

    }//GEN-LAST:event_jButton13ActionPerformed

    JButton searchButtons[] = new JButton[70];
    int flag2=0;
    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String searchString = jTextField1.getText();
        ArrayList<ItemModel> searchList = SearchController.enterItemToSearch(searchString);
        jPanel2.setLayout(new GridLayout(0,3));
//        JButton itemlist1;
        JPanel itemPanel;
        JLabel itemLabel;
        jPanel2.removeAll();
        int index=0;
//        if(flag8 == 0) {
        for (ItemModel item : searchList) {

                itemPanel = new JPanel();
                itemPanel.setLayout(new GridBagLayout());
                GridBagConstraints c = new GridBagConstraints();
                //                itemPanel.setLayout(new BorderLayout());
//                    itemlist1 = new JButton();
                searchButtons[index] = new JButton();
                searchButtons[index].addActionListener(listener2);
                itemLabel = new JLabel("<html>" + item.getName() + "<br>" + item.getPrice() + "</html>");

                ImageIcon imageIcon = new ImageIcon(item.getImagePath()); // load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it
                Image newimg = image.getScaledInstance(120, 120, Image.SCALE_FAST); // scale it the smooth way
                imageIcon = new ImageIcon(newimg);  // transform it back
//                    itemlist1.setIcon(imageIcon); // NOI18N
//                    itemlist1.setName(String.valueOf(item.getItemID()));
                searchButtons[index].setIcon(imageIcon); // NOI18N
                searchButtons[index].setName(String.valueOf(item.getItemID()));
                //                itemlist1.setBorder(null);
                //                itemlist1.setBorderPainted(false);
                //                itemlist1.setContentAreaFilled(false);
                //                itemlist1.setMargin(new java.awt.Insets(0, 0, 0, 0));

                c.fill = GridBagConstraints.BOTH;
                c.ipady = 40;      //make this component tall
                c.weightx = 0.0;
                c.gridwidth = 3;
                c.gridx = 0;
                c.gridy = 0;
//                    itemPanel.add(itemlist1, c);
                itemPanel.add(searchButtons[index], c);
//                    buttons[index].addActionListener();
//
//                    public void actionPerformed(ActionEvent e) {
//                        String hexColor = e.getSource().getText();
//                        getContentPane().setBackground(Color.decode(hexColor));
//
//                    };

                c.fill = GridBagConstraints.CENTER;
                c.weightx = 0.0;
                c.gridx = 0;
                c.gridy = 1;
                itemPanel.add(itemLabel, c);
                jPanel2.add(itemPanel);
                jScrollPane2.setViewportView(jPanel2);
                index++;
//                }



        }
        flag4 = 1;
        jPanel2.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        repaint();
        validate();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       render2("");
        repaint();
        validate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt) throws ClassNotFoundException {//GEN-FIRST:event_jButton3ActionPerformed
        shoppingCartView frame = new shoppingCartView();
        frame.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(ActionEvent evt) {
        render3("");
    }

    private void jButton5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        render4("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        render5("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        render6("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        render7("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();
        return resizedImg;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton10;
    private JButton jButton13;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton9;
    private JLabel jLabel2;
    private JLayeredPane jLayeredPane1;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenu jMenu3;
    private JMenu jMenu4;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItem1;
    private JMenuItem jMenuItem2;
    private JMenuItem jMenuItem3;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JScrollPane jScrollPane7;
    private JScrollPane jScrollPane8;
    private JSplitPane jSplitPane1;
    private JTextField jTextField1;
    private JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
